module.exports = [{
    "id": "db0",
    "i": "db0",
    "type": "map",
    "empty": "empty",
    "x": 3,
    "y": 0,
    "w": 8,
    "h": 3,
    "nodes": [{
        "group": "Default",
        "visibility": true,
        "title": "OrtofotoRegione2010",
        "description": "geosolutions:OrtofotoRegione2010",
        "name": "Ortofoto Regione",
        "id": "001-0"
    }]
}, {
    "id": "db1",
    "type": "text",
    "x": 0,
    "y": 1,
    "w": 3,
    "h": 6,
    "i": "db1",
    "text": "<p><span style=\"color: rgb(34, 34, 34);\">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui do</span><strong style=\"color: rgb(34, 34, 34);\">lorem ipsum</strong><span style=\"color: rgb(34, 34, 34);\">, quia&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">dolor sit, amet, consectetur, adipisci</strong><span style=\"color: rgb(34, 34, 34);\">&nbsp;v</span><strong style=\"color: rgb(34, 34, 34);\">elit, sed</strong><span style=\"color: rgb(34, 34, 34);\">&nbsp;quia non numquam&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">eius mod</strong><span style=\"color: rgb(34, 34, 34);\">i&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">tempor</strong><span style=\"color: rgb(34, 34, 34);\">a&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">incidunt, ut labore et dolore magna</strong><span style=\"color: rgb(34, 34, 34);\">m&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">aliqua</strong><span style=\"color: rgb(34, 34, 34);\">m quaerat voluptatem.&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">Ut enim ad minim</strong><span style=\"color: rgb(34, 34, 34);\">a&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">veniam, quis nostru</strong><span style=\"color: rgb(34, 34, 34);\">m&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">exercitation</strong><span style=\"color: rgb(34, 34, 34);\">em&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">ullam co</strong><span style=\"color: rgb(34, 34, 34);\">rporis suscipit</span><strong style=\"color: rgb(34, 34, 34);\">&nbsp;labori</strong><span style=\"color: rgb(34, 34, 34);\">o</span><strong style=\"color: rgb(34, 34, 34);\">s</strong><span style=\"color: rgb(34, 34, 34);\">am,&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">nisi ut aliquid ex ea commodi consequat</strong><span style=\"color: rgb(34, 34, 34);\">ur?&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">Quis aute</strong><span style=\"color: rgb(34, 34, 34);\">m vel eum&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">iure reprehenderit,</strong><span style=\"color: rgb(34, 34, 34);\">&nbsp;qui&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">in</strong><span style=\"color: rgb(34, 34, 34);\">&nbsp;ea&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">voluptate velit esse</strong><span style=\"color: rgb(34, 34, 34);\">, quam nihil molestiae&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">c</strong><span style=\"color: rgb(34, 34, 34);\">onsequatur, vel&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">illum</strong><span style=\"color: rgb(34, 34, 34);\">, qui&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">dolore</strong><span style=\"color: rgb(34, 34, 34);\">m&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">eu</strong><span style=\"color: rgb(34, 34, 34);\">m&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">fugiat</strong><span style=\"color: rgb(34, 34, 34);\">, quo voluptas&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">nulla pariatur</strong><span style=\"color: rgb(34, 34, 34);\">? [33] At vero eos et accusamus et iusto odio dignissimos ducimus, qui blanditiis praesentium voluptatum deleniti atque corrupti, quos dolores et quas molestias&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">exceptur</strong><span style=\"color: rgb(34, 34, 34);\">i&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">sint, obcaecat</strong><span style=\"color: rgb(34, 34, 34);\">i&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">cupiditat</strong><span style=\"color: rgb(34, 34, 34);\">e&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">non pro</strong><span style=\"color: rgb(34, 34, 34);\">v</span><strong style=\"color: rgb(34, 34, 34);\">ident</strong><span style=\"color: rgb(34, 34, 34);\">, similique&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">sunt in culpa</strong><span style=\"color: rgb(34, 34, 34);\">,&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">qui officia deserunt mollit</strong><span style=\"color: rgb(34, 34, 34);\">ia&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">anim</strong><span style=\"color: rgb(34, 34, 34);\">i,&nbsp;</span><strong style=\"color: rgb(34, 34, 34);\">id est laborum</strong><span style=\"color: rgb(34, 34, 34);\">&nbsp;et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio, cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet, ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.</span></p>"
}, {
    "id": "db2",
    "type": "text",
    "x": 0,
    "y": 0,
    "w": 3,
    "h": 1,
    "i": "db2",
    "text": "<p><strong class=\"ql-size-large\"><span class=\"ql-cursor\">﻿</span>My Dashboard﻿</strong></p>"
}, {
    "id": "db3",
    "type": "legend",
    "x": 11,
    "y": 0,
    "w": 1,
    "h": 3,
    "i": "db3",
    "selectedMap": {
        "id": "db0",
        "i": "db0",
        "type": "map",
        "empty": "empty",
        "x": 0,
        "y": 0,
        "w": 6,
        "h": 3,
        "nodes": [{
            "group": "Default",
            "visibility": true,
            "title": "OrtofotoRegione2010",
            "description": "geosolutions:OrtofotoRegione2010",
            "name": "Ortofoto Regione",
            "id": "001-0"
        }]
    },
    "isConnected": true
}, {
    "id": "db4",
    "i": "db4",
    "type": "chart",
    "x": 3,
    "y": 3,
    "w": 4,
    "h": 2,
    "chartType": "line",
    "selectedMap": {}
}, {
    "id": "db5",
    "i": "db5",
    "type": "table",
    "x": 8,
    "y": 3,
    "w": 4,
    "h": 4
}, {
    "id": "db6",
    "i": "db6",
    "type": "chart",
    "x": 3,
    "y": 5,
    "w": 4,
    "h": 2,
    "chartType": "bar",
    "selectedMap": {}
}, {
    "id": "db7",
    "i": "db7",
    "type": "chart",
    "x": 7,
    "y": 3,
    "w": 1,
    "h": 4,
    "chartType": "pie",
    "selectedMap": {}
}];
